Guest/urls.py
from django.urls import path
from Guest import views

app_name = 'Guest'

urlpatterns = [
    path('login/', views.login, name="login"),
    path('userregister/', views.register, name="register"),
    path('sellerregister/', views.sellerregister, name="sellerregister"),
    path('index/', views.index, name="index"),
    path('Tnx/', views.Thankyou, name="thankyou"),
    path('ebook_list/', views.ebook_list, name="ebook_list"),
    path('Product/<int:book_id>/', views.Productd, name="Productd"),
    path('Ebookdisp/<int:bbook_id>/', views.Ebookdisp, name="Ebookdisp"),
    path('seller-info/<int:book_id>/', views.book_seller_info, name='book_seller_info'),
    path('ViewReview/<int:book_id>/', views.displayreviews, name='Guest_book_reviews'),
    path('EGuestauthor-detail/<int:ebook_id>/', views.Guest_author_detail_view, name='Guestauthor_detail'),
    path('ebook/<int:ebook_id>/reviews/', views.Guest_view_ebook_reviews, name='Guest_view_ebook_reviews'),


]

User/urls.py
from django.urls import path
from User import views

app_name = 'User'

urlpatterns = [
        path('userhome/', views.homeuser, name="userhome"),
        path('tnxshop/', views.tnxshop, name="tnxshop"),
        path('Cart/<int:cid>/', views.cart_view, name='cart'),
        path('updateuser/<int:cid>/',views.updateuser,name="Updateuser"),
        path('ViewProfile/',views.userdetails,name="View-userProfile"),
        path('payment/<int:pid>',views.payment,name="payment"),
        path('bookingdetailsofuser/', views.view_booking, name="bookingdetailsUser"),
        path('Productdetail/<int:book_id>/', views.Productdetail, name="Product"),
        path('ebooklistUser/', views.ebooklistUser, name="ebooklistUser"),
        path('EbookUserdisp/<int:bbook_id>/', views.EbookdispUser, name="Ebookdispuser"),
        path('seller-infoUser/<int:book_id>/', views.book_sellerinfo, name='book_sellerinfo'),
        path('Add-review/<int:book_id>/', views.review, name='Addreview'),
        path('ViewReview/<int:book_id>/', views.display_reviews, name='book_reviews'),
        path('Complaint/', views.complaint, name="Complaint"),
        path('ECart/<int:bbook_id>/', views.Ecart_view, name='Ecart'), 
        path('Epayment/<int:pid>/', views.Epayment, name="Epayment"),
        path('payment/success/<int:pid>/', views.payment_success, name='payment_success'),
        path('download/<int:pid>/', views.download_ebook, name='download_ebook'),
        path('author-detail/<int:ebook_id>/', views.author_detail_view, name='author_detail'),
        path('update_profile/<int:cid>/', views.update_profile, name='update_profile'),
        path('update_password/<int:cid>/', views.update_password, name='update_password'),
        path('User/Track/<int:booking_id>/', views.track_order, name='track'),
        path('order-details/<int:booking_id>/', views.view_order_details, name='order_details'),
        path('add-ebook-review/<int:ebook_id>/', views.add_ebook_review, name='add_ebook_review'),
        path('ebook/<int:ebook_id>/reviews/', views.view_ebook_reviews, name='view_ebook_reviews'),
]

ebook/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from Guest import urls, views
from Admin import urls
from BookAuthor import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Guest/',include('Guest.urls')),
    path('Admin/',include('Admin.urls')),
    path('BookAuthor/',include('BookAuthor.urls')),
    path('User/',include('User.urls')),
    path('',views.index,name="index"),
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

BookAuthor/models.py
from django.db import models

from Guest.models import NewSeller


class Book(models.Model):
    CATEGORY_CHOICES = [
        ('Fiction', 'Fiction'),
        ('Non-Fiction', 'Non-Fiction'),
        ('Science Fiction', 'Science Fiction'),
        ('Mystery', 'Mystery'),
        ('Thriller', 'Thriller'),
        ('Fantasy', 'Fantasy'),
        ('Biography', 'Biography'),
    ]

    book_name = models.CharField(max_length=100)
    book_cover_image = models.ImageField(upload_to='book_covers/')
    author_name = models.CharField(max_length=100)
    author_image = models.ImageField(upload_to='author_images/')
    book_price = models.DecimalField(max_digits=10, decimal_places=2)
    book_description = models.TextField()
    book_category = models.CharField(max_length=100, choices=CATEGORY_CHOICES)
    seller_name = models.CharField(max_length=100)
    seller_email = models.EmailField()
    seller_phone = models.CharField(max_length=15)
    seller_description = models.TextField()
    seller_location = models.CharField(max_length=100)
    seller_license_number = models.CharField(max_length=50)
    SellerAdd=models.ForeignKey(NewSeller,on_delete=models.SET_NULL,null=True)



class EBook(models.Model):
    CATEGORY_CHOICES = [
        ('Fiction', 'Fiction'),
        ('Non-Fiction', 'Non-Fiction'),
        ('Science Fiction', 'Science Fiction'),
        ('Mystery', 'Mystery'),
        ('Thriller', 'Thriller'),
        ('Fantasy', 'Fantasy'),
        ('Biography', 'Biography'),
    ]

    book_name = models.CharField(max_length=100)
    book_cover_image = models.ImageField(upload_to='book_covers/')
    author_name = models.CharField(max_length=100)
    book_price = models.DecimalField(max_digits=10, decimal_places=2)
    book_description = models.TextField()
    book_category = models.CharField(max_length=100, choices=CATEGORY_CHOICES)
    seller_name = models.CharField(max_length=100)
    author_image = models.ImageField(upload_to='author_images/')
    seller_email = models.EmailField()
    seller_phone = models.CharField(max_length=15)
    seller_description = models.TextField()
    seller_location = models.CharField(max_length=100)
    seller_license_number = models.CharField(max_length=50)
    book_file = models.FileField(upload_to='ebooks/', blank=True, null=True)
    SellerEAdd=models.ForeignKey(NewSeller,on_delete=models.SET_NULL,null=True)

Guest/models.py
from django.db import models



class Newuser(models.Model):
        Firstname=models.CharField(max_length=30)
        Lastname=models.CharField(max_length=30)
        Email=models.EmailField(unique=True)
        Street=models.CharField(max_length=30)
        Address=models.TextField(unique=True)
        Zipcode=models.CharField(max_length=30)
        Place=models.CharField(max_length=30)
        Country=models.CharField(max_length=30)
        PhnCode=models.CharField(max_length=20)
        PhnNumber=models.CharField(max_length=15)
        Password=models.CharField(unique=True,max_length=20)
        
        
        
class NewSeller(models.Model):
        Name=models.CharField(max_length=30)
        Contact=models.CharField(max_length=20)
        Email=models.EmailField(unique=True)
        Address=models.TextField(unique=True)
        Registername=models.CharField(max_length=30)
        AuthorLicno=models.CharField(max_length=20)
        Proof1 = models.CharField(max_length=20,)
        Proof2 = models.CharField(max_length=20,)
        Password=models.CharField(unique=True,max_length=20)
        vstatus=models.IntegerField(default=0)

        

        
        

    
    




class Complaint(models.Model):
    COMPLAINT_CHOICES = [
        ('Service', 'Service'),
        ('Product', 'Product'),
        ('Delivery', 'Delivery'),
        ('Others', 'Others'),
    ]

    complaint_type = models.CharField(max_length=20, choices=COMPLAINT_CHOICES, default='Others')
    complaint_details = models.TextField()
    customer_name = models.CharField(max_length=100)
    customer_email = models.EmailField()
    customer_phone = models.CharField(max_length=15)

User/models.py
from django.db import models
from BookAuthor.models import Book, EBook

from Guest.models import NewSeller, Newuser

# Create your models here.
class Cart(models.Model):
    Bookbooking=models.ForeignKey(Book,on_delete=models.SET_NULL,null=True)
    EBookbooking=models.ForeignKey(EBook,on_delete=models.SET_NULL,null=True)
    Booking1_Date=models.DateField(auto_now=True)
    b1_status = models.BooleanField(default=True)
    p_status = models.BooleanField(default=True)
    User1=models.ForeignKey(Newuser,on_delete=models.SET_NULL,null=True)
    Seller = models.ForeignKey(NewSeller, on_delete=models.SET_NULL, null=True)
    
    
        
class Review(models.Model):
    RATING_CHOICES = [
        (5, 'Excellent'),
        (4, 'Very Good'),
        (3, 'Good'),
        (2, 'Fair'),
        (1, 'Poor'),
    ]
    Bookdetail=models.ForeignKey(Book,on_delete=models.SET_NULL,null=True)
    EBookdetail=models.ForeignKey(EBook,on_delete=models.SET_NULL,null=True)
    rating = models.IntegerField(choices=RATING_CHOICES)
    comment = models.TextField()

Guest/views.py
from django.shortcuts import get_object_or_404, redirect, render
from Admin.models import Admintable

from BookAuthor.models import Book, EBook
from User.models import Review
from .models import*


def login(request):
    if request.method=="POST":
        email=request.POST.get('logemail')
        Pass=request.POST.get('logpass')
        Ulogin=Newuser.objects.filter(Email=email,Password=Pass).count()
        Slogin=NewSeller.objects.filter(Email=email,Password=Pass,vstatus=True).count()
        Alogin=Admintable.objects.filter(admin_email=email,admin_password=Pass).count()
        if Ulogin > 0:
            uadmin=Newuser.objects.get(Email=email,Password=Pass)
            request.session['uid']=uadmin.id
            return redirect('User:userhome')
        elif Slogin > 0:
            sadmin=NewSeller.objects.get(Email=email,Password=Pass,vstatus=1)
            request.session['sid']=sadmin.id
            return redirect('BookAuthor:authorhome')
        elif Alogin > 0:
            aadmin=Admintable.objects.get(admin_email=email,admin_password=Pass)
            request.session['aid']=aadmin.id
            return redirect('Admin:AdminHome')
        else:
            error="Invalid Credentials!!"
            return render(request,"Guest/Login.html",{'ERR':error})
    else:
        return render(request, "Guest/Login.html")



def register(request):
    if request.method=='POST':
        Newuser.objects.create(Firstname=request.POST.get('first_name'),Lastname=request.POST.get('last_name'),Email=request.POST.get('user_email'),
         Street=request.POST.get('street'),Address=request.POST.get('address'),Zipcode=request.POST.get('zip_code'),
         Place=request.POST.get('place'),Country=request.POST.get('country'),PhnCode=request.POST.get('ph_code'),PhnNumber=request.POST.get('phn_number'),
         Password=request.POST.get('password'))
        return render(request,"Guest/Thankyou.html")
    else:
        register=Newuser.objects.all()
        return render(request,"Guest/Register.html")
    
        

def sellerregister(request):
    if request.method == "POST":
        NewSeller.objects.create(
            Name=request.POST.get('txt_name'),
            Contact=request.POST.get('txt_contact'),
            Email=request.POST.get('txt_email'),
            Address=request.POST.get('txt_address'),
            Registername=request.POST.get('txt_registername'),
            AuthorLicno=request.POST.get('txt_licensenumber'),
            Proof1=request.POST.get('image_proof1'),
            Proof2=request.POST.get('image_proof2'),  
            Password=request.POST.get('password')
        )
        return render(request, "Guest/Thankyou.html")
    else:
        sellerregister=NewSeller.objects.all()
        return render(request, "Guest/Seller.html")



def index(request):
    viewbook=Book.objects.all()
    return render(request,"Guest/index.html",{'data':viewbook})




def Thankyou(request):
    return render(request, "Guest/ThankYou.html")




def Productd(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    return render(request, "Guest/Product.html", {'book': book})

def ebook_list(request):
    ebooks = EBook.objects.all()
    return render(request, "Guest/Ebook.html", {'ebooks': ebooks})

def Ebookdisp(request, bbook_id):
    ebook = get_object_or_404(EBook, pk=bbook_id)
    return render(request, "Guest/Ebookdisplay.html", {'ebook': ebook})

def book_seller_info(request, book_id):
    book = Book.objects.get(pk=book_id)
    return render(request, "Guest/book_seller_info.html", {'book': book})

def displayreviews(request, book_id):
    book = Book.objects.get(pk=book_id)
    book_reviews = Review.objects.filter(Bookdetail_id=book_id)
    return render(request, "Guest/GuestViewReview.html", {'book_reviews': book_reviews, 'book_name': book.book_name})

def Guest_author_detail_view(request, ebook_id):
    ebook = get_object_or_404(EBook, pk=ebook_id)
    return render(request, 'Guest/EGuestAuthor.html', {'ebook': ebook})

def Guest_view_ebook_reviews(request, ebook_id):
    ebook =EBook.objects.get(pk=ebook_id)
    reviews = Review.objects.filter(EBookdetail=ebook)
    
    return render(request, "Guest/GuestEViewReview.html", {'ebook': ebook, 'reviews': reviews})

Guest/templates/Guest/Ebook.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Online Book Store</title>
  <!-- stylesheet -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  <!-- min.css -->
  <link rel="stylesheet" href="/Guest/templates/Guest/bootstrap.min.css">
  <!-- Icons -->
  <script src="https://kit.fontawesome.com/675ad92f7a.js" crossorigin="anonymous"></script>
  <style>
    .card-link {
      text-decoration: none;
      /* Remove underline from the card link */
      color: inherit;
      /* Inherit text color from parent */
    }

    /* Custom styles for the card */
    .card {
      border: 1px solid #ddd;
      border-radius: 8px;
      overflow: hidden;
      transition: box-shadow 0.3s ease;
    }

    .card:hover {
      box-shadow: 0 2px 60px rgba(0, 0, 0, 0.1);
    }

    .card img {
      width: 100%;
      height: 250px;
      object-fit: cover;
    }

    .card-body .read-more {
      text-align: left;
    }


    .card-body {
      display: flex;
      flex-direction: column;
      justify-content: space-between;
      height: 100%;
      border: solid 1px rgb(253, 253, 253);
    }

    .card-body form {
      margin-top: auto;
    }

    .card-title {
      font-size: 1.2rem;
      font-weight: bold;
      margin-bottom: 10px;
    }

    .card-text {
      color: #555;
    }

    .btn-primary {
      background-color: #007bff;
      color: #fff;
      border: none;
      border-radius: 5px;
      padding: 8px 16px;
      transition: background-color 0.3s ease;
    }

    .btn-primary:hover {
      background-color: #0056b3;
    }



    .breadcrumb-chevron {
      --bs-breadcrumb-divider: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='16' height='16' fill='%236c757d'%3E%3Cpath fill-rule='evenodd' d='M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708z'/%3E%3C/svg%3E");
      gap: .5rem;
    }

    .breadcrumb-chevron .breadcrumb-item {
      display: flex;
      gap: inherit;
      align-items: center;
      padding-left: 0;
      line-height: 1;
    }

    .breadcrumb-chevron .breadcrumb-item::before {
      gap: inherit;
      float: none;
      width: 1rem;
      height: 1rem;
    }

    .breadcrumb-custom .breadcrumb-item {
      position: relative;
      flex-grow: 1;
      padding: .75rem 3rem;
    }

    .breadcrumb-custom .breadcrumb-item::before {
      display: none;
    }

    .breadcrumb-custom .breadcrumb-item::after {
      position: absolute;
      top: 50%;
      right: -25px;
      z-index: 1;
      display: inline-block;
      width: 50px;
      height: 50px;
      margin-top: -25px;
      content: "";
      background-color: var(--bs-tertiary-bg);
      border-top-right-radius: .5rem;
      box-shadow: 1px -1px var(--bs-border-color);
      transform: scale(.707) rotate(45deg);
    }

    .breadcrumb-custom .breadcrumb-item:first-child {
      padding-left: 1.5rem;
    }

    .breadcrumb-custom .breadcrumb-item:last-child {
      padding-right: 1.5rem;
    }

    .breadcrumb-custom .breadcrumb-item:last-child::after {
      display: none;
    }

    .book-highlight {
      font-family: 'Arial', sans-serif;
      font-weight: bold;
      font-size: 24px;
      color: #1a73e8; /* Change the color to your preference */
    }
    
    .rotated-letter {
      display: inline-block;
      transform: rotate(-5deg);
      color: #ff4081; /* Change the color to your preference */
    }
    a{
      text-decoration: none;
    }
    
  </style>
</head>

<body>
  <!-- Navbar -->
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'Guest:ebook_list' %}">
        Online <span class="book-highlight">B<span class="rotated-letter">O</span>OK</span> Store
    </a>      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02"
        aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'Guest:login' %}">LOGIN</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'Guest:register' %}">SignUP</a>
          </li>
        </ul>
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>
  <!-- End Navbar -->

  <!-- Carousel -->
  <div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
      <!-- Add your carousel items here -->
      <div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="https://i.postimg.cc/7LvNCZJ6/giammarco-boscaro-ze-H-ljaw-Htg-unsplash.jpg"
                    class="d-block w-100" alt="First Slide" style="height: 90vh;">
                <div class="carousel-caption d-none d-md-block text-start">
                    <h1 style="color: white;">Welcome to Our Online Bookstore!</h1>
                    <h3 style="color: white;">Discover a vast collection of books from various genres and authors. Dive into thrilling stories, gain knowledge from insightful reads, and find your next favorite book here.</h3>
                </div>
            </div>
            <div class="carousel-item">
                <img src="https://i.postimg.cc/rsY1qVLq/chuttersnap-Zf64-Osndqvc-unsplash.jpg"
                    class="d-block w-100" alt="Second Slide" style="height: 90vh;">
                <div class="carousel-caption d-none d-md-block text-start">
                    <h1>Explore New Releases and Bestsellers</h1>
                    <h3>Stay updated with the latest releases and bestsellers in literature, fiction, non-fiction, and more. Our bookstore brings you the most sought-after titles from renowned authors.</h3>
                </div>
            </div>
            <div class="carousel-item">
                <img src="https://i.postimg.cc/6qSvDMd3/inaki-del-olmo-NIJu-EQw0-RKg-unsplash.jpg"
                    class="d-block w-100" alt="Third Slide" style="height: 90vh;">
                <div class="carousel-caption d-none d-md-block text-start">
                    <h1 style="color: white;">Join Our Reading Community</h1>
                    <h3 style="color: white;">Connect with other book lovers, participate in discussions, share your thoughts on books, and explore recommendations. Embrace the joy of reading together!</h3>
                </div>
            </div>
        </div>
    </div>
  <!-- End Carousel -->
  <!-- bread crubs -->

  <div class="container my-5">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb breadcrumb-custom overflow-hidden text-center bg-body-tertiary border rounded-3">
        <li class="breadcrumb-item">
          <a class="link-body-emphasis fw-semibold text-decoration-none" href="{% url 'Guest:index' %}">
            <svg class="bi" width="16" height="16">
              <use xlink:href="#house-door-fill"></use>
            </svg>
            Home
          </a>
        </li>
        <li class="breadcrumb-item">
          <a class="link-body-emphasis fw-semibold text-decoration-none" href="{% url 'Guest:ebook_list' %}">Ebook</a>
        </li>
      </ol>
    </nav>
  </div>

  <!-- bread crumbs end -->
  <div class="container mt-4">
    <div class="row">
      {% for ebook in ebooks %}
      <div class="col-md-4 mb-3">
        <a href="{% url 'Guest:Ebookdisp' ebook.id %}" class="card-link">
          <div class="card">
            <img src="{{ ebook.book_cover_image.url }}" class="card-img-top" alt="{{ ebook.book_name }}">
            <div class="card-body">
              <h5 class="card-title">{{ ebook.book_name }}</h5>
              <p class="card-text" id="description_{{ book.id }}">{{ ebook.book_description | truncatechars:100 }}</p>
              {% if ebook.book_description|length > 100 %}

              <a href="{% url 'User:Ebookdispuser' ebook.id %}"> Read More></a>
              <br>
              {% endif %}
              <p><strong>Author:</strong> <a href="{% url 'Guest:Guestauthor_detail' ebook_id=ebook.id %}">{{ ebook.author_name }}</a></p>
                            <p class="card-text">Price: ${{ ebook.book_price }}</p>
              <!-- Add more details or buttons as needed -->
            </div>
          </div>
        </a>
      </div>
      {% endfor %}
    </div>
  </div>


  <footer class="text-white text-center text-lg-start bg-dark">
    <!-- Grid container -->
    <div class="container p-4">
        <!--Grid row-->
        <div class="row mt-4">
            <!--Grid column-->
            <div class="col-lg-4 col-md-12 mb-4 mb-md-0">
                <h5 class="text-uppercase mb-4" style="color: white;">About Our Bookstore</h5>
                <p>
                    Discover a wide range of books from various genres and authors at our online bookstore. Dive into
                    captivating stories, gain knowledge from insightful reads, and find your next favorite book here.
                </p>
                <p>
                    Connect with other book lovers, participate in discussions, share your thoughts on books, and explore
                    recommendations. Embrace the joy of reading together!
                </p>
                <div class="mt-4">
                    <!-- Social media icons -->
                    <a type="button" class="btn btn-floating btn-light btn-lg"><i class="fab fa-facebook-f"></i></a>
                    <a type="button" class="btn btn-floating btn-light btn-lg"><i class="fab fa-twitter"></i></a>
                    <a type="button" class="btn btn-floating btn-light btn-lg"><i class="fab fa-instagram"></i></a>
                    <a type="button" class="btn btn-floating btn-light btn-lg"><i class="fab fa-pinterest"></i></a>
                </div>
            </div>
            <!--Grid column-->

            <!--Grid column-->
            <div class="col-lg-4 col-md-6 mb-4 mb-md-0">
                <h5 class="text-uppercase mb-4 pb-1" style="color: white;">Search Our Store</h5>
                <div class="form-outline form-white mb-4">
                    <input type="text" id="searchInput" class="form-control form-control-lg" />
                    <label class="form-label" for="searchInput">Search</label>
                </div>
                <ul class="fa-ul" style="margin-left: 1.65em;">
                    <li class="mb-3">
                        <span class="fa-li"><i class="fas fa-map-marker-alt"></i></span><span
                            class="ms-2">Online Bookstore, Worldwide</span>
                    </li>
                    <li class="mb-3">
                        <span class="fa-li"><i class="fas fa-envelope"></i></span><span
                            class="ms-2">contact@onlinebookstore.com</span>
                    </li>
                    <li class="mb-3">
                        <span class="fa-li"><i class="fas fa-phone"></i></span><span class="ms-2">+1 234 567 890</span>
                    </li>
                </ul>
            </div>
            <!--Grid column-->

            <!--Grid column-->
            <div class="col-lg-4 col-md-6 mb-4 mb-md-0">
                <h5 class="text-uppercase mb-4" style="color: white;">Store Hours</h5>
                <table class="table text-center text-white">
                    <tbody class="fw-normal">
                        <tr>
                            <td>Mon - Fri:</td>
                            <td>24hrs</td>
                        </tr>
                        <tr>
                            <td>Saturday:</td>
                            <td> 24hrs</td>
                        </tr>
                        <tr>
                            <td>Sunday:</td>
                            <td>24hrs</td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <!--Grid column-->
        </div>
        <!--Grid row-->
    </div>
    <!-- Grid container -->

    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
        © 2023 Online Bookstore. All Rights Reserved.
        <a class="text-white" href="#">Terms of Service</a>
        <a class="text-white" href="#">Privacy Policy</a>
    </div>
    <!-- Copyright -->
</footer>



  <!-- Bootstrap Bundle with Popper.js -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
    crossorigin="anonymous"></script>
    <script>
      function toggleDescription(bookId) {
        var description = document.getElementById('description_' + bookId);
        var btnText = document.getElementById('readMoreBtn_' + bookId);
  
        if (description.style.display === 'none' || description.style.display === '') {
          description.style.display = 'block';
          btnText.innerHTML = 'Read Less';
        } else {
          description.style.display = 'none';
          btnText.innerHTML = 'Read More';
        }
      }
    </script>
</body>

</html>

Guest/templates/Guest/GuestEViewReview.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Book Reviews</title>

    <style>
        /* Center the card within the webpage */
        body {
            display: flex;
            justify-content: center;
            align-items: center;
            margin: 0;
            font-family: Arial, sans-serif;
        }

        .card-container {
            max-width: 600px;
            width: 100%;
            padding: 20px;
        }

        /* Styling for the card */
        .card {
            border: 1px solid #ccc;
            border-radius: 5px;
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
            padding: 20px;
            margin-bottom: 20px;
        }

        .card p {
            margin: 5px 0;
        }
    </style>
</head>

<body>
    <div align="center" class="card-container">


        <h1>Reviews for <span  style="color: red;">{{ebook.book_name }}</span> </h1>
        <ul>
            {% for review in reviews %}
            <li>
                <div class="card">
                    <p><strong>Rating:</strong> {{ review.get_rating_display }}</p>
                    <hr>
                    <p><strong>Comment:</strong> {{ review.comment }}</p>
                </div>
            </li>
            {% empty %}
            <li>No reviews yet.</li>
            {% endfor %}
        </ul>
    </div>
</body>

</html>