BookAuthor/urls.py
from django.urls import path
from BookAuthor import views

app_name = 'BookAuthor'

urlpatterns = [

path('authorhome/', views.authorhome, name="authorhome"),
path('addbook/',views.addbook,name="addbook"), 
path('authorprofile/',views.Authorprofile,name="authprofile"), 
path('AddEbook/',views.AddEbook,name="AddEbook"), 
path('seller-bookings/', views.seller_view_bookings, name='seller_bookings'),
path('seller-added-books/', views.seller_added_books, name='seller_added_books'),
path('update_seller_profile/<int:cid>/', views.update_seller_profile, name='update_seller_profile'),
path('Sellerupdate_password/<int:cid>/', views.Seller_update_password, name='seller_update_password'),


]

Guest/urls.py
from django.urls import path
from Guest import views

app_name = 'Guest'

urlpatterns = [
    path('login/', views.login, name="login"),
    path('userregister/', views.register, name="register"),
    path('sellerregister/', views.sellerregister, name="sellerregister"),
    path('index/', views.index, name="index"),
    path('Tnx/', views.Thankyou, name="thankyou"),
    path('ebook_list/', views.ebook_list, name="ebook_list"),
    path('Product/<int:book_id>/', views.Productd, name="Productd"),
    path('Ebookdisp/<int:bbook_id>/', views.Ebookdisp, name="Ebookdisp"),
    path('seller-info/<int:book_id>/', views.book_seller_info, name='book_seller_info'),
    path('ViewReview/<int:book_id>/', views.displayreviews, name='Guest_book_reviews'),
    path('EGuestauthor-detail/<int:ebook_id>/', views.Guest_author_detail_view, name='Guestauthor_detail'),
    path('ebook/<int:ebook_id>/reviews/', views.Guest_view_ebook_reviews, name='Guest_view_ebook_reviews'),


]

User/urls.py
from django.urls import path
from User import views

app_name = 'User'

urlpatterns = [
        path('userhome/', views.homeuser, name="userhome"),
        path('tnxshop/', views.tnxshop, name="tnxshop"),
        path('Cart/<int:cid>/', views.cart_view, name='cart'),
        path('updateuser/<int:cid>/',views.updateuser,name="Updateuser"),
        path('ViewProfile/',views.userdetails,name="View-userProfile"),
        path('payment/<int:pid>',views.payment,name="payment"),
        path('bookingdetailsofuser/', views.view_booking, name="bookingdetailsUser"),
        path('Productdetail/<int:book_id>/', views.Productdetail, name="Product"),
        path('ebooklistUser/', views.ebooklistUser, name="ebooklistUser"),
        path('EbookUserdisp/<int:bbook_id>/', views.EbookdispUser, name="Ebookdispuser"),
        path('seller-infoUser/<int:book_id>/', views.book_sellerinfo, name='book_sellerinfo'),
        path('Add-review/<int:book_id>/', views.review, name='Addreview'),
        path('ViewReview/<int:book_id>/', views.display_reviews, name='book_reviews'),
        path('Complaint/', views.complaint, name="Complaint"),
        path('ECart/<int:bbook_id>/', views.Ecart_view, name='Ecart'), 
        path('Epayment/<int:pid>/', views.Epayment, name="Epayment"),
        path('payment/success/<int:pid>/', views.payment_success, name='payment_success'),
        path('download/<int:pid>/', views.download_ebook, name='download_ebook'),
        path('author-detail/<int:ebook_id>/', views.author_detail_view, name='author_detail'),
        path('update_profile/<int:cid>/', views.update_profile, name='update_profile'),
        path('update_password/<int:cid>/', views.update_password, name='update_password'),
        path('User/Track/<int:booking_id>/', views.track_order, name='track'),
        path('order-details/<int:booking_id>/', views.view_order_details, name='order_details'),
        path('add-ebook-review/<int:ebook_id>/', views.add_ebook_review, name='add_ebook_review'),
        path('ebook/<int:ebook_id>/reviews/', views.view_ebook_reviews, name='view_ebook_reviews'),
]

ebook/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from Guest import urls, views
from Admin import urls
from BookAuthor import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Guest/',include('Guest.urls')),
    path('Admin/',include('Admin.urls')),
    path('BookAuthor/',include('BookAuthor.urls')),
    path('User/',include('User.urls')),
    path('',views.index,name="index"),
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

BookAuthor/models.py
from django.db import models

from Guest.models import NewSeller


class Book(models.Model):
    CATEGORY_CHOICES = [
        ('Fiction', 'Fiction'),
        ('Non-Fiction', 'Non-Fiction'),
        ('Science Fiction', 'Science Fiction'),
        ('Mystery', 'Mystery'),
        ('Thriller', 'Thriller'),
        ('Fantasy', 'Fantasy'),
        ('Biography', 'Biography'),
    ]

    book_name = models.CharField(max_length=100)
    book_cover_image = models.ImageField(upload_to='book_covers/')
    author_name = models.CharField(max_length=100)
    author_image = models.ImageField(upload_to='author_images/')
    book_price = models.DecimalField(max_digits=10, decimal_places=2)
    book_description = models.TextField()
    book_category = models.CharField(max_length=100, choices=CATEGORY_CHOICES)
    seller_name = models.CharField(max_length=100)
    seller_email = models.EmailField()
    seller_phone = models.CharField(max_length=15)
    seller_description = models.TextField()
    seller_location = models.CharField(max_length=100)
    seller_license_number = models.CharField(max_length=50)
    SellerAdd=models.ForeignKey(NewSeller,on_delete=models.SET_NULL,null=True)



class EBook(models.Model):
    CATEGORY_CHOICES = [
        ('Fiction', 'Fiction'),
        ('Non-Fiction', 'Non-Fiction'),
        ('Science Fiction', 'Science Fiction'),
        ('Mystery', 'Mystery'),
        ('Thriller', 'Thriller'),
        ('Fantasy', 'Fantasy'),
        ('Biography', 'Biography'),
    ]

    book_name = models.CharField(max_length=100)
    book_cover_image = models.ImageField(upload_to='book_covers/')
    author_name = models.CharField(max_length=100)
    book_price = models.DecimalField(max_digits=10, decimal_places=2)
    book_description = models.TextField()
    book_category = models.CharField(max_length=100, choices=CATEGORY_CHOICES)
    seller_name = models.CharField(max_length=100)
    author_image = models.ImageField(upload_to='author_images/')
    seller_email = models.EmailField()
    seller_phone = models.CharField(max_length=15)
    seller_description = models.TextField()
    seller_location = models.CharField(max_length=100)
    seller_license_number = models.CharField(max_length=50)
    book_file = models.FileField(upload_to='ebooks/', blank=True, null=True)
    SellerEAdd=models.ForeignKey(NewSeller,on_delete=models.SET_NULL,null=True)

BookAuthor/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render

from Guest.models import  NewSeller, Newuser
from User.models import Cart
from .models import*


# Create your views here.

def authorhome(request):
    author=NewSeller.objects.get(id=request.session["sid"])
    return render(request,"BookAuthor/AuthorHome.html")



def Authorprofile(request):
    author=NewSeller.objects.get(id=request.session["sid"])
    return render(request, "BookAuthor/AuthorProfile.html",{'auth':author})

def addbook(request):
    if request.method == 'POST':
        book = Book(
            book_name=request.POST.get('bookName'),
            book_cover_image=request.FILES.get('bookImage'),
            author_name=request.POST.get('authorName'),
            author_image=request.FILES.get('authorimage'),
            book_price=request.POST.get('bookPrice'),
            book_description=request.POST.get('bookDescription'),
            book_category=request.POST.get('bookCategory'),
            seller_name=request.POST.get('sellerName'),
            seller_email=request.POST.get('sellerEmail'),
            seller_phone=request.POST.get('sellerPhone'),
            seller_description=request.POST.get('sellerDescription'),
            seller_location=request.POST.get('sellerLocation'),
            seller_license_number=request.POST.get('sellerLicense')
        )
        book.save()
    return render(request,"BookAuthor/Addbook.html")




def AddEbook(request):
    if request.method == 'POST':
        book = EBook(
            book_name=request.POST.get('bookName'),
            book_cover_image=request.FILES.get('bookImage'),
            author_name=request.POST.get('authorName'),
            book_price=request.POST.get('bookPrice'),
            book_description=request.POST.get('bookDescription'),
            book_category=request.POST.get('bookCategory'),
            seller_name=request.POST.get('sellerName'),
            author_image=request.FILES.get('authorimage'),
            seller_email=request.POST.get('sellerEmail'),
            seller_phone=request.POST.get('sellerPhone'),
            seller_description=request.POST.get('sellerDescription'),
            seller_location=request.POST.get('sellerLocation'),
            seller_license_number=request.POST.get('sellerLicense'),
            book_file=request.FILES.get('bookFile')
        )
        book.save()
    return render(request,"BookAuthor/AddEbook.html")





def seller_view_bookings(request):
    if 'sid' in request.session:
        seller_id = request.session['sid']
        seller_bookings = Cart.objects.filter(Seller_id=seller_id)
        
        context = {
            'seller_bookings': seller_bookings,
        }
        return render(request, "BookAuthor/seller_bookings.html", context)
    else:
        return HttpResponse("Seller ID not found in session. Please log in as a seller.")



def seller_added_books(request):
    if 'sid' in request.session:  
        seller_id = request.session['sid']
        physical_books = Book.objects.filter(SellerAdd_id=seller_id)
        ebooks = EBook.objects.filter(SellerEAdd_id=seller_id)

        context = {
            'physical_books': physical_books,
            'ebooks': ebooks,
        }
        return render(request, "BookAuthor/seller_added_books.html", context)
    else:
        return HttpResponse("Seller ID not found in session. Please log in as a seller.")
    
    
def update_seller_profile(request, cid):
    seller = NewSeller.objects.get(id=cid)
    
    if request.method == "POST":
        seller.Name = request.POST.get("txt_name")
        seller.Contact = request.POST.get("txt_contact")
        seller.Email = request.POST.get("txt_email")
        seller.Address = request.POST.get("txt_address")
        seller.Registername = request.POST.get("txt_register_name")
        seller.save()
        
        return redirect('BookAuthor:update_seller_profile', cid=seller.id)
    
    return render(request, "BookAuthor/Sellerupdate_profile.html", {"seller": seller})




def Seller_update_password(request, cid):
    try:
        seller = NewSeller.objects.get(id=cid)
    except NewSeller.DoesNotExist:
        return render(request, "User/Update_password.html", {"error_message": "User does not exist."})

    if request.method == "POST":
        current_password = request.POST.get("current_password")
        new_password = request.POST.get("new_password")
        confirm_password = request.POST.get("confirm_password")

        if not seller.Password == current_password:
            return render(request, "User/Update_password.html", {"error_message": "Incorrect current password."})

        if new_password != confirm_password:
            return render(request, "User/Update_password.html", {"error_message": "New passwords do not match."})

        seller.Password = new_password
        seller.save()

        return redirect('Guest:login')  

    return render(request, "User/Update_password.html", {"seller": seller})

BookAuthor/templates/BookAuthor/AuthorHome.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>Author Home</title>
   <!-- bs-s -->
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
   integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
 <!-- Icons -->
 <script src="https://kit.fontawesome.com/675ad92f7a.js" crossorigin="anonymous"></script>
 <!-- min -->
 <link rel="stylesheet" href="/BookAuthor/templates/BookAuthor/bootstrap.min.css">
<!-- bs-j -->
 <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
   integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
   crossorigin="anonymous"></script>
  <style>
    /* Add your custom styles here */
    /* Example styles for the cover page */
    .cover {
      height: 100vh; /* Full viewport height */
      display: flex;
      justify-content: center;
      align-items: center;
      text-align: center;
      background-image: url('https://example.com/your-cover-image.jpg'); /* Replace with your cover image URL */
      background-size: cover;
      background-position: center;
      color: rgb(12, 12, 12);
      font-size: 3rem;
    }
    .book-highlight {
      font-family: 'Arial', sans-serif;
      font-weight: bold;
      font-size: 24px;
      color: #1a73e8; /* Change the color to your preference */
    }
    
    .rotated-letter {
      display: inline-block;
      transform: rotate(-5deg);
      color: #ff4081; /* Change the color to your preference */
    }
  </style>
</head>

<body>

  <!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'BookAuthor:authorhome' %}">
      Online <span class="book-highlight">B<span class="rotated-letter">O</span>OK</span> Store
  </a>    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02"
      aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'BookAuthor:seller_bookings' %}">View Booking</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'BookAuthor:addbook' %}">Add Book</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'BookAuthor:AddEbook' %}">Add Ebook</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'BookAuthor:authprofile' %}">View Profile</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'BookAuthor:seller_added_books' %}">Book's Added By seller</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'Guest:index' %}">Logout</a>
        </li>
      </ul>
    </div>
  </nav>
  <!-- nav end -->
  <!-- cover page -->
  <div class="cover">
    <div>
      <h1>Welcome, Seller!</h1>
      <p> Thank you for being part of our book selling community. Start managing your books, view sales, and engage with buyers to grow your business.</p>
    </div>
  </div>
<!-- Footer -->
<footer class="text-white text-center text-lg-start bg-dark">
  <!-- Grid container -->
  <div class="container p-4">
      <!--Grid row-->
      <div class="row mt-4">
          <!--Grid column-->
          <div class="col-lg-4 col-md-12 mb-4 mb-md-0">
              <h5 class="text-uppercase mb-4" style="color: white;">About Our Bookstore</h5>
              <p>
                  Discover a wide range of books from various genres and authors at our online bookstore. Dive into
                  captivating stories, gain knowledge from insightful reads, and find your next favorite book here.
              </p>
              <p>
                  Connect with other book lovers, participate in discussions, share your thoughts on books, and explore
                  recommendations. Embrace the joy of reading together!
              </p>
              <div class="mt-4">
                  <!-- Social media icons -->
                  <a type="button" class="btn btn-floating btn-light btn-lg"><i class="fab fa-facebook-f"></i></a>
                  <a type="button" class="btn btn-floating btn-light btn-lg"><i class="fab fa-twitter"></i></a>
                  <a type="button" class="btn btn-floating btn-light btn-lg"><i class="fab fa-instagram"></i></a>
                  <a type="button" class="btn btn-floating btn-light btn-lg"><i class="fab fa-pinterest"></i></a>
              </div>
          </div>
          <!--Grid column-->

          <!--Grid column-->
          <div class="col-lg-4 col-md-6 mb-4 mb-md-0">
              <h5 class="text-uppercase mb-4 pb-1" style="color: white;">Search Our Store</h5>
              <div class="form-outline form-white mb-4">
                  <input type="text" id="searchInput" class="form-control form-control-lg" />
                  <label class="form-label" for="searchInput">Search</label>
              </div>
              <ul class="fa-ul" style="margin-left: 1.65em;">
                  <li class="mb-3">
                      <span class="fa-li"><i class="fas fa-map-marker-alt"></i></span><span
                          class="ms-2">Online Bookstore, Worldwide</span>
                  </li>
                  <li class="mb-3">
                      <span class="fa-li"><i class="fas fa-envelope"></i></span><span
                          class="ms-2">contact@onlinebookstore.com</span>
                  </li>
                  <li class="mb-3">
                      <span class="fa-li"><i class="fas fa-phone"></i></span><span class="ms-2">+1 234 567 890</span>
                  </li>
              </ul>
          </div>
          <!--Grid column-->

          <!--Grid column-->
          <div class="col-lg-4 col-md-6 mb-4 mb-md-0">
              <h5 class="text-uppercase mb-4" style="color: white;">Store Hours</h5>
              <table class="table text-center text-white">
                  <tbody class="fw-normal">
                      <tr>
                          <td>Mon - Fri:</td>
                          <td>24hrs</td>
                      </tr>
                      <tr>
                          <td>Saturday:</td>
                          <td> 24hrs</td>
                      </tr>
                      <tr>
                          <td>Sunday:</td>
                          <td>24hrs</td>
                      </tr>
                  </tbody>
              </table>
          </div>
          <!--Grid column-->
      </div>
      <!--Grid row-->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
      © 2023 Online Bookstore. All Rights Reserved.
      <a class="text-white" href="#">Terms of Service</a>
      <a class="text-white" href="#">Privacy Policy</a>
  </div>
  <!-- Copyright -->
</footer>

<!-- End Footer -->

  <!-- Bootstrap JS CDN -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>

BookAuthor/templates/BookAuthor/AuthorProfile.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>Author Home</title>
 <!-- bs-s -->
 <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
 integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<!-- Icons -->
<script src="https://kit.fontawesome.com/675ad92f7a.js" crossorigin="anonymous"></script>
<!-- min -->
<link rel="stylesheet" href="/BookAuthor/templates/BookAuthor/bootstrap.min.css">
<!-- bs-j -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
 integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
 crossorigin="anonymous"></script>  <style>
    .book-highlight {
      font-family: 'Arial', sans-serif;
      font-weight: bold;
      font-size: 24px;
      color: #1a73e8;
    }
    
    .rotated-letter {
      transform: rotate(-5deg);
      color: #ff4081; 
    } 

    body {
      font-family: Arial, sans-serif;
      background-color: #f0f0f0;
      height: 100vh;
      justify-content: center;
      align-items: center;
      margin: 0;
  }

  /* Card Styles */
  .card {
      width: 100%;
      max-width: 400px;
      margin-top: 20px;
      border-radius: 8px;
      box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);

    }

  .card-header {
      color: darkred;
      border-bottom: 1px solid #ccc;
      padding: 15px;
  }

  .card-body {
      padding: 20px;
  }

  .btn {
      display: inline-block;
      padding: 10px 20px;
      margin-top: 10px;
      text-decoration: none;
      color: #fff;
      background-color: #007bff;
      border: none;
      border-radius: 4px;
      cursor: pointer;
      transition: background-color 0.3s;
  }

  .btn-primary {
      background-color: #007bff;
  }

  .btn-primary:hover {
      background-color: #0056b3;
  }

  </style>
</head>

<body>

  <!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'BookAuthor:authorhome' %}">
      Online <span class="book-highlight">B<span class="rotated-letter">O</span>OK</span> Store
  </a>    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02"
      aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'BookAuthor:seller_bookings' %}">View Booking</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'BookAuthor:addbook' %}">Add Book</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'BookAuthor:AddEbook' %}">Add Ebook</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'BookAuthor:authprofile' %}">View Profile</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'Guest:index' %}">Logout</a>
        </li>
      </ul>
    </div>
  </nav>
  <br><br>

 



  <div class="container mt-4">
    <!-- Display user profile information -->
    <div class="card">
        <div class="card-header">
            <h2>Author Profile</h2>
        </div>
        <div class="card-body">
            <!-- Display user profile data -->
            <p><strong>Name:</strong> {{ auth.Name }}</p>
            <p><strong>Contact:</strong> {{ auth.Contact }}</p>
            <p><strong>Email:</strong> {{ auth.Email }}</p>
            <p><strong>Address:</strong> {{ auth.Address }}</p>
            <p><strong>Registered Name:</strong> {{ auth.Registername }}</p>
            <p><strong>Author License Number:</strong> {{ auth.AuthorLicno }}</p>
            <!-- Links for editing profile and changing password -->
            <a href="{% if auth.id %}{% url 'BookAuthor:update_seller_profile' cid=auth.id %}{% endif %}"
                class="btn btn-primary">Edit Profile</a>
            <a href="{% if auth.id %}{% url 'BookAuthor:seller_update_password' cid=auth.id %}{% endif %}" class="btn btn-primary">Change Password</a>
        </div>
    </div>
</div>







<br><br>
<!-- Footer -->
<footer class="text-white text-center text-lg-start bg-dark">
  <!-- Grid container -->
  <div class="container p-4">
      <!--Grid row-->
      <div class="row mt-4">
          <!--Grid column-->
          <div class="col-lg-4 col-md-12 mb-4 mb-md-0">
              <h5 class="text-uppercase mb-4" style="color: white;">About Our Bookstore</h5>
              <p>
                  Discover a wide range of books from various genres and authors at our online bookstore. Dive into
                  captivating stories, gain knowledge from insightful reads, and find your next favorite book here.
              </p>
              <p>
                  Connect with other book lovers, participate in discussions, share your thoughts on books, and explore
                  recommendations. Embrace the joy of reading together!
              </p>
              <div class="mt-4">
                  <!-- Social media icons -->
                  <a type="button" class="btn btn-floating btn-light btn-lg"><i class="fab fa-facebook-f"></i></a>
                  <a type="button" class="btn btn-floating btn-light btn-lg"><i class="fab fa-twitter"></i></a>
                  <a type="button" class="btn btn-floating btn-light btn-lg"><i class="fab fa-instagram"></i></a>
                  <a type="button" class="btn btn-floating btn-light btn-lg"><i class="fab fa-pinterest"></i></a>
              </div>
          </div>
          <!--Grid column-->

          <!--Grid column-->
          <div class="col-lg-4 col-md-6 mb-4 mb-md-0">
              <h5 class="text-uppercase mb-4 pb-1" style="color: white;">Search Our Store</h5>
              <div class="form-outline form-white mb-4">
                  <input type="text" id="searchInput" class="form-control form-control-lg" />
                  <label class="form-label" for="searchInput">Search</label>
              </div>
              <ul class="fa-ul" style="margin-left: 1.65em;">
                  <li class="mb-3">
                      <span class="fa-li"><i class="fas fa-map-marker-alt"></i></span><span
                          class="ms-2">Online Bookstore, Worldwide</span>
                  </li>
                  <li class="mb-3">
                      <span class="fa-li"><i class="fas fa-envelope"></i></span><span
                          class="ms-2">contact@onlinebookstore.com</span>
                  </li>
                  <li class="mb-3">
                      <span class="fa-li"><i class="fas fa-phone"></i></span><span class="ms-2">+1 234 567 890</span>
                  </li>
              </ul>
          </div>
          <!--Grid column-->

          <!--Grid column-->
          <div class="col-lg-4 col-md-6 mb-4 mb-md-0">
              <h5 class="text-uppercase mb-4" style="color: white;">Store Hours</h5>
              <table class="table text-center text-white">
                  <tbody class="fw-normal">
                      <tr>
                          <td>Mon - Fri:</td>
                          <td>24hrs</td>
                      </tr>
                      <tr>
                          <td>Saturday:</td>
                          <td> 24hrs</td>
                      </tr>
                      <tr>
                          <td>Sunday:</td>
                          <td>24hrs</td>
                      </tr>
                  </tbody>
              </table>
          </div>
          <!--Grid column-->
      </div>
      <!--Grid row-->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
      © 2023 Online Bookstore. All Rights Reserved.
      <a class="text-white" href="#">Terms of Service</a>
      <a class="text-white" href="#">Privacy Policy</a>
  </div>
  <!-- Copyright -->
</footer>

<!-- End Footer -->
  <!-- Bootstrap JS CDN -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>